"use client";

import { MessageContent } from "./message-content";
import { FormEvent, useEffect, useRef, useState } from "react";

type Message = { role: "user" | "assistant"; content: string };
const emptyContext={messages:[] as Message[],candidates:[],route:null,tripState:{area:null,start_point:null,available_minutes:null,need_meal:null,member:"不限",member_explicit:false,member_selection_requested:false,start_latitude:null,start_longitude:null,start_display_name:null,ordinary_restaurant_consent:null}};

function MapView({route}:{route:any}){
  const mapRef=useRef<any>(null);const layersRef=useRef<any[]>([]);
  useEffect(()=>{let timer:number|undefined;const render=()=>{const L=(window as any).L;if(!L){timer=window.setTimeout(render,100);return}if(!mapRef.current){mapRef.current=L.map("map",{zoomControl:true}).setView([35.665,139.736],14);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(mapRef.current)}layersRef.current.forEach((layer)=>layer.remove());layersRef.current=[];if(!route?.map)return;const points=route.map.route_coordinates.map(([lon,lat]:number[])=>[lat,lon]);const line=L.polyline(points,{color:"#65459a",weight:6,opacity:.9,dashArray:route.map.geometry_source==="straight_line_fallback"?"10 9":null,lineCap:"round"}).addTo(mapRef.current);layersRef.current.push(line);route.map.markers.forEach((marker:any)=>{const icon=L.divIcon({className:`numbered-marker ${marker.kind}`,html:String(marker.sequence),iconSize:[32,32],iconAnchor:[16,16]});const node=L.marker([marker.latitude,marker.longitude],{icon}).bindPopup(`<strong>${String(marker.name).replace(/[<>&]/g,"")}</strong>`).addTo(mapRef.current);layersRef.current.push(node)});mapRef.current.fitBounds(L.latLngBounds(points),{padding:[42,42],maxZoom:16});setTimeout(()=>mapRef.current.invalidateSize(),80)};render();return()=>{if(timer)clearTimeout(timer)}},[route]);
  return <div className="map-wrap"><div id="map" aria-label="可缩放巡礼路线地图"/>{!route&&<div className="map-empty"><div className="map-empty-mark">⌖</div><p>完成地点查询后，这里会显示可缩放地图和步行线路。</p></div>}</div>;
}

export default function Home(){
  const [context,setContext]=useState<any>(emptyContext);const [messages,setMessages]=useState<Message[]>([{role:"assistant",content:"告诉我想去的区域、出发地点和可用时间。我会查询巡礼地点、安排用餐，并计算步行路线。"}]);
  const [memory,setMemory]=useState<any[]>([]);const [quick,setQuick]=useState<string[]>(["体验示例","只说部分条件"]);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const listRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("sakamichi-live-session")||"null");if(saved){setContext(saved.context);setMessages(saved.messages);setMemory(saved.memory||[]);setQuick(saved.quick||[])}}catch{}},[]);
  useEffect(()=>{try{localStorage.setItem("sakamichi-live-session",JSON.stringify({context,messages,memory,quick}))}catch{}listRef.current?.scrollTo({top:listRef.current.scrollHeight,behavior:"smooth"})},[context,messages,memory,quick]);
  const send=async(text:string)=>{const value=text.trim();if(!value||busy)return;setBusy(true);setError("");setQuick([]);setMessages((old)=>[...old,{role:"user",content:value}]);setInput("");try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:value,context})});const data:any=await response.json();if(!response.ok)throw new Error(data.error||"规划服务暂时不可用");setContext(data.context);setMessages((old)=>[...old,{role:"assistant",content:data.assistant}]);setMemory(data.tripState||[]);setQuick(data.quickReplies||[])}catch(reason){const text=reason instanceof Error?reason.message:"服务暂时不可用";setError(text);setMessages((old)=>[...old,{role:"assistant",content:`暂时无法继续规划：${text}` }])}finally{setBusy(false)}};
  const submit=(event:FormEvent)=>{event.preventDefault();send(input)};
  const reset=()=>{setContext(emptyContext);setMessages([{role:"assistant",content:"新对话已开始。告诉我区域、起点和可用时间，我会从确认条件开始规划。"}]);setMemory([]);setQuick(["体验示例","只说部分条件"]);setError("");localStorage.removeItem("sakamichi-live-session")};
  const route=context.route;
  return <div className="app-shell">
    <header className="app-header"><div className="brand"><span className="status-dot"/><div><h1>坂道巡礼 Agent</h1></div></div><nav className="header-actions"><button className="text-button" onClick={()=>(document.querySelector("#aboutDialog") as HTMLDialogElement)?.showModal()}>作品说明</button><button className="text-button" disabled={busy} onClick={reset}>新对话</button></nav></header>
    <main className="workspace">
      <section className="chat-panel"><div className="memory-bar">{memory.length?memory.map((item)=><span className="memory-chip" key={item.key}>{item.label}：{item.value}</span>):<span>尚未确认规划条件</span>}</div>
        <div className="messages" ref={listRef}>{messages.map((message,index)=><article className={`message-row ${message.role==="user"?"user-row":"assistant-row"}`} key={index}>{message.role==="assistant"&&<div className="avatar">坂</div>}<div className={`message ${message.role==="user"?"user-message":"assistant-message"} ${error&&index===messages.length-1?"error-message":""}`}>{message.role === "assistant" ? <MessageContent text={message.content}/> : <p>{message.content}</p>}</div></article>)}{busy&&<article className="message-row assistant-row"><div className="avatar">坂</div><div className="message assistant-message loading-message"><i/><i/><i/></div></article>}</div>
        <div className="quick-replies">{quick.map((label)=><button key={label} disabled={busy} onClick={()=>send(label==="体验示例"?"我想从六本木站出发，在港区巡礼4小时，需要安排用餐，只看中嶋優月相关地点。":label==="只说部分条件"?"我想在港区巡礼":label)}>{label}</button>)}</div>
        <form className="composer" onSubmit={submit}><textarea value={input} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send(input)}}} rows={1} maxLength={500} placeholder="描述你的巡礼计划……"/><button className="send-button" disabled={busy}>发送</button></form><p className="composer-note">地点来自公开数据快照，出行前请核实营业状态。</p>
      </section>
      <aside className="result-panel"><div className="result-heading"><div><span className="eyebrow">路线地图</span><h2>{route?`${route.area || ""}巡礼路线`:"等待规划"}</h2></div><span className="route-status">{route?`${route.stops.length}站 · 约${route.estimated_total_minutes}分钟`:"尚无路线"}</span></div><MapView route={route}/>{route?.start_display_name&&<p className="source-note">起点：{route.start_display_name}</p>}{context.dataInfo&&<p className="source-note">地点更新于 {new Date(context.dataInfo.fetched_at).toLocaleString("zh-CN")} · {context.dataInfo.record_count} 条{context.dataInfo.refresh_failed?" · 更新暂不可用，使用最近可用数据":""}。历史关联不代表活动仍在举行。</p>}
        {route&&<><div className="route-summary">{[["步行",`${route.total_walking_minutes}分钟`],["停留与用餐",`${route.total_visit_minutes}分钟`],["剩余缓冲",`${route.buffer_minutes}分钟`]].map(([label,value])=><div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}{route.map.geometry_notice&&<div className="map-notice">{route.map.geometry_notice}</div>}</div><div className="route-stops">{route.stops.map((stop:any,index:number)=><article className="stop-card" key={stop.id}><span className={`stop-number ${stop.category==="餐厅"?"restaurant":""}`}>{stop.sequence}</span><div><strong>{stop.name}</strong><small>{stop.summary}</small><small>{stop.source_type==="ordinary_restaurant"?"普通餐厅 · 非巡礼地点":stop.address}</small><a href={stop.source_url} target="_blank" rel="noreferrer">查看地点来源 ↗</a></div><span className="stop-time">{`${route.legs[index]?.walking_minutes||0}分钟步行 · ${stop.assumed_visit_minutes}分钟停留`}</span></article>)}</div></>}
      </aside>
    </main>
    <dialog id="aboutDialog" className="about-dialog"><form method="dialog" className="dialog-card"><button className="dialog-close" value="close">×</button><span className="eyebrow">作品说明</span><h2>从自然语言需求到可执行路线</h2><p>大模型负责理解上下文与选择工具，服务端负责权限校验、地点筛选和路线计算。新对话会清空全部状态，成员“不限”会覆盖之前的成员限制。</p><dl><div><dt>巡礼地点</dt><dd>SakuMap公开地点快照</dd></div><div><dt>普通餐厅</dt><dd>OpenStreetMap / Overpass</dd></div><div><dt>步行路线</dt><dd>OSRM foot profile</dd></div><div><dt>地图</dt><dd>Leaflet + OpenStreetMap</dd></div></dl></form></dialog>
  </div>;
}
